/* ============================================================
   ITEM ICONS — original 16x16 pixel-art sprites for the
   hotbar, drawn procedurally so they match the blocky style of
   the world without borrowing any existing game's assets.
   ============================================================ */

const S = 16;

/* Each sprite is a 16-row list of 16-char strings. '.' = transparent.
   Hand-authored in the same chunky language as the world. */
const SPRITES = {
  home: `
................
.....HHHHHH.....
....H......H....
...H........H...
...H..WWWW..H...
...H..W..W..H...
...H..W..W..H...
...H..WWWW..H...
...H........H...
..H..........H..
..H...LLLL...H..
..H...L..L...H..
..HHH......HHH..
.HHHH....HHHH...
................
................`,

  book: `
................
.......BBB......
......BWWWB.....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
.....BWWWWWB....
......BBBBB.....
................
................`,

  sword: `
................
...........PP...
..........PPP...
.........PPP....
........PPP.....
.......PPP......
......PPP.......
.....PPP........
..SSPPP.........
..SSS............
..SS.............
..S..............
.S...............
................
................
................`,

  compass: `
................
.......KK.......
......KWWK......
.....KWWWWK.....
....KWWKKWWK....
...KWWK.KWWK...
..KWK.....KWK..
..KWK.....KWK..
..KWK.....KWK..
...KWK...KWK....
....KWWKWWK.....
.....KWWWWK.....
......KWWK......
.......KK.......
................
................`,

  gem: `
................
.......MM.......
......MMMM......
......MwwM......
.....MwwwwM.....
.....MwwwwM.....
....MwwwwwwM....
....MwwwwwwM....
...MwwwwwwwwM...
...MwwwwwwwwM...
..MwwwwwwwwwwM..
...MwwwwwwwwM...
....MMMMMMMM....
................
................
................`,

  mail: `
................
....AAAAAAAA....
...A........A...
...A.BBBBB..A...
...A.BB..BB.A...
...A.B....B.A...
...A.BB..BB.A...
...A.B....B.A...
...A.BBBBB..A...
...A........A...
....AAAAAAAA....
................
................
................
................
................`
};

/* Palette per icon: index -> [key, color] */
const PALETTE = {
  home:    { H: '#8b5a2b', L: '#c98a4b', W: '#8ed0f0' },
  book:    { B: '#6b3fa0', W: '#e6dcc8' },
  sword:   { P: '#c8ccd4', S: '#6b4a2b' },
  compass: { K: '#3a3a44', W: '#7fd4f0' },
  gem:     { M: '#3fd0d8', w: '#bff6f8' },
  mail:    { A: '#9a6a4a', B: '#f0e8d8' }
};

/**
 * Renders an icon to a canvas at `scale` device-independent pixels
 * per sprite pixel.
 */
export function iconCanvas(name, scale = 3) {
  const art = SPRITES[name];
  const cv = document.createElement('canvas');
  cv.width = cv.height = S * scale;
  const ctx = cv.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  if (!art) return cv;
  const pal = PALETTE[name] || {};
  const rows = art.replace(/^\n/, '').split('\n');
  for (let y = 0; y < rows.length && y < S; y++) {
    const row = rows[y];
    for (let x = 0; x < row.length && x < S; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      // deterministic shade jitter so sprites are not flat vector fills
      const base = pal[ch] || '#c0c0c0';
      const n = ((x * 7 + y * 13) % 5) - 2;
      ctx.fillStyle = shade(base, n * 4);
      ctx.fillRect(x * scale, y * scale, scale, scale);
    }
  }
  return cv;
}

/** Multiply a hex colour by a brightness delta. */
function shade(hex, amt) {
  const n = parseInt(hex.slice(1), 16);
  const r = clamp((n >> 16) + amt), g = clamp(((n >> 8) & 255) + amt), b = clamp((n & 255) + amt);
  return '#' + ((r << 16) | (g << 8) | b).toString(16).padStart(6, '0');
}
function clamp(v) { return v < 0 ? 0 : v > 255 ? 255 : v | 0; }

/**
 * Draws a beveled "held item" 3D-ish version of a flat sprite:
 * the sprite on the front face, a darkened copy on the top face
 * skewed up-right, and another on the right face. This is what
 * sells it as an in-world item rather than a UI icon.
 */
export function itemCanvas(name, scale = 3) {
  const base = iconCanvas(name, scale);
  const w = base.width, h = base.height;
  const d = Math.max(3, Math.round(w * 0.30));      // isometric depth
  const cv = document.createElement('canvas');
  cv.width = w + d;
  cv.height = h + d;
  const ctx = cv.getContext('2d');
  ctx.imageSmoothingEnabled = false;

  // top face
  ctx.save();
  ctx.setTransform(1, 0, -0.45, 0.45, d, 0);
  ctx.drawImage(darken(base, 0.42), 0, 0, w, h);
  ctx.restore();

  // right face
  ctx.save();
  ctx.setTransform(0.45, 0.45, 0, 1, w, 0);
  ctx.drawImage(darken(base, 0.24), 0, 0, w, h);
  ctx.restore();

  // front face
  ctx.drawImage(base, 0, 0);
  return cv;
}

function darken(canvas, amt) {
  const cv = document.createElement('canvas');
  cv.width = canvas.width; cv.height = canvas.height;
  const c = cv.getContext('2d');
  c.drawImage(canvas, 0, 0);
  c.globalCompositeOperation = 'source-atop';
  c.fillStyle = `rgba(0,0,0,${amt})`;
  c.fillRect(0, 0, cv.width, cv.height);
  return cv;
}

/** Decorative 2D "creative-mode" block icon used on the hotbar. */
export function blockIconCanvas(tileName, scale = 3) {
  // lazy import avoided: caller passes a painted canvas factory
  return tileName(scale);
}
